# Generated by Django 4.0.4 on 2022-08-26 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.PROTECT, to='news.category'),
        ),
    ]
